# Change these first
owner: mass-im # Your GitHub organization or username, where this repository lives
repo: forest-status-test # The name of this repository

sites:
  - name: Forest.host
    url: https://forest.host
  - name: api.forest.host
    url: https://api.forest.host/v1/auth/providers
  - name: api.tinytrees.nl
    url: https://api.tinytrees.nl/v1/auth/providers
  - name: app.forest.host
    url: https://app.forest.host/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /forest-status-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Forest status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
    #navbar:
    #- title: Status
    #href: /
    #- title: GitHub
    #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
