# Change these first
owner: mass-im # Your GitHub organization or username, where this repository lives
repo: forest-status-test # The name of this repository

sites:
  - name: api.tinytrees.nl
    url: https://api.tinytrees.nl/v1/auth/providers
  - name: app.forest.host
    url: https://app.forest.host/
  - name: Leaf.cloud network
    url: $LEAF_URL
    __dangerous__body_down: '"Status":"Down"'
  - name: balancer0
    check: "tcp-ping"
    url: 45.135.56.67
  - name: compute0
    check: "tcp-ping"
    url: 45.135.56.231
  - name: compute1
    check: "tcp-ping"
    url: 45.135.56.97
  - name: compute2
    check: "tcp-ping"
    url: 45.135.56.134

status-website:
  themeUrl: https://cdn.statically.io/gh/mass-im/forest-status-test/master/assets/forest.css
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /forest-status-test
  logoUrl: https://raw.githubusercontent.com/mass-im/forest-status-test/master/assets/forest-icon.svg
  name: Forest.host platform status
    #introTitle: "**Forest** is the open-source uptime monitor and status page, powered entirely by GitHub."
    #navbar:
    #- title: Status
    #href: /
    #- title: GitHub
    #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
